name: Build PDF Document
on: push

env:
  INPUT_MD: "submission.md"
  OUTPUT_TEX: "submission.tex"
  OUTPUT_PDF_PDFLATEX: "submission.pdf"
  OUTPUT_PDF: "1-checkpoint.pdf"
  WRITEUPS_FOLDER: "writeups"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Check Writeup Diffs
        uses: tj-actions/changed-files@v35
        id: changed-files
        with:
          dir_names: "true"
          dir_names_exclude_root: "true"
          files: writeups
          json: true
      - name: List all changed files
        run: echo '**Changed Directories**<${{ steps.changed-files.outputs.all_changed_and_modified_files }}>'
      - name: Send output
        id: set-matrix
        run: echo "::set-output name=matrix::{\"container\":${{ steps.changed-files.outputs.all_changed_and_modified_files }}}"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
  
  
  convert_via_pandoc:
    needs: [setup]
    runs-on: ubuntu-latest
    if: ${{ needs.setup.outputs.matrix != '' && toJson(fromJSON(needs.setup.outputs.matrix).container) != '[]' }}
    strategy:
      matrix:
        directory: ${{ fromJSON(needs.setup.outputs.matrix).container }}
    steps:
      - name: Log directory
        run: |
          echo "**DOING**: <${{ matrix.directory }}>"
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Install pandoc template
        run: |
          wget https://github.com/Wandmalfarbe/pandoc-latex-template/releases/download/v2.3.0/Eisvogel-2.3.0.zip
          unzip -d eisvogel Eisvogel-2.3.0.zip
          mkdir -p ~/.pandoc/templates/
          cp eisvogel/eisvogel.latex ~/.pandoc/templates/
      - name: MD to TEX file
        uses: docker://pandoc/core:2.9
        with:
          args: >- # allows you to break string into multiple lines
            -s
            --template eisvogel/eisvogel.latex
            --listings
            -H disable_float.tex
            -V colorlinks=true
            -V linkcolor=blue
            -V urlcolor=blue
            --output=${{ env.WRITEUPS_FOLDER }}/${{ matrix.directory }}/${{ env.OUTPUT_TEX }}
            ${{ env.WRITEUPS_FOLDER }}/${{ matrix.directory }}/${{ env.INPUT_MD }}
      - name: TEX to PDF file
        uses: xu-cheng/latex-action@v2
        with:
          work_in_root_file_dir: true
          root_file: ${{ env.WRITEUPS_FOLDER }}/${{ matrix.directory }}/${{ env.OUTPUT_TEX }}
          post_compile: "latexmk -c"
      - name: Rename PDF file
        run: mv ${{ env.WRITEUPS_FOLDER }}/${{ matrix.directory }}/${{ env.OUTPUT_PDF_PDFLATEX }} ${{ env.WRITEUPS_FOLDER }}/${{ matrix.directory }}/${{ env.OUTPUT_PDF }}
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: ${{ env.WRITEUPS_FOLDER }}/${{ matrix.directory }}/${{ env.OUTPUT_PDF }}
